### ISSUE TITLE
Image Assets

### ISSUE THREAD

**Issue by AquaAllen** [sfbrigade/localfreeweb.org#3]
I need to create some images.

**Comment by jeremiak** [comment]
Make sure to use the @ to get a hold of us when you upload those images.

Like so: @AquaAllen

**Comment by AquaAllen** [comment]
@jeremiak
I was wondering if we could make a few adjustments:
Header 100 px ht
showcase 300 px ht
I've attached an image of the "free-web", which is 300 px ht. Not sure how to make image responsive, or how to keep text from running over the computer part of the image, it can run over the "rays". Let me know if you need something else
/Users/allen/Dropbox/Code for America/local free web/images/free-web-art_02.png

**Comment by jeremiak** [comment]
@AquaAllen you didn't include the image, it just the path to that file on your computer.

Can you describe these changes a bit more? Maybe with an app like [Skitch](http://evernote.com/skitch/) or something?

In any case, these changes look pretty easy so just update this thread and we can get them all worked out
