### ISSUE TITLE
Add a footer

### ISSUE THREAD

**Issue by msecret** [sfbrigade/localfreeweb.org#8]
Types of information:
- Github repo for site
- Github repo for the text api
- Code for America San Francisco brigade
- Copyright, licence? 
- Acknowledgements? 
- Where the data comes from?

**Comment by msecret** [comment]
More to potentially add:
- Team members (I think github profiles would be a cool touch with name and profile pic)
- Contact information for adding to your own city
- MUNI bus stop codes list.

**Comment by msecret** [comment]
@jtanigawa @jeremiak @AquaAllen I'd like to add a section for contributers. can somebody give me all the names and maybe github profile urls? I'll add links to github profiles if they use github.

**Comment by msecret** [comment]
AllenMeyerDesign.com  - Alan

**Comment by msecret** [comment]
j6design github (Julio Feliciano)

**Comment by msecret** [comment]
Jeremia K link to github

**Comment by msecret** [comment]
Joseph link to github

**Comment by msecret** [comment]
@brittag Let me know how you would like to be referenced in the contributers section that will be in the footer. Format is as follows:

Name (first and last, just first, github profile, whatever) 
Link to something (optional)

**Comment by brittag** [comment]
Cool, thanks! Britta G with link to https://twitter.com/brittagus is fine

**Comment by j6design** [comment]
Please add Junying Du and Jay Nunez (helped translate flyer)
